<?php

namespace PhpUnitsOfMeasureTest\PhysicalQuantity;

use PhpUnitsOfMeasure\PhysicalQuantity\Volume;

class VolumeTest extends AbstractPhysicalQuantityTestCase
{
    protected $supportedUnitsWithAliases = [
        'm^3',
        'm³',
        'cubic meter',
        'cubic meters',
        'cubic metre',
        'cubic metres',
        'MTQ',
        'mm^3',
        'mm³',
        'cubic millimeter',
        'cubic millimeters',
        'cubic millimetre',
        'cubic millimetres',
        'cm^3',
        'cm³',
        'cubic centimeter',
        'cubic centimeters',
        'cubic centimetre',
        'cubic centimetres',
        'CMQ',
        'dm^3',
        'dm³',
        'cubic decimeter',
        'cubic decimeters',
        'cubic decimetre',
        'cubic decimetres',
        'DMQ',
        'km^3',
        'km³',
        'cubic kilometer',
        'cubic kilometers',
        'cubic kilometre',
        'cubic kilometres',
        'ft^3',
        'ft³',
        'cubic foot',
        'cubic feet',
        'FTQ',
        'in^3',
        'in³',
        'cubic inch',
        'cubic inches',
        'INQ',
        'yd^3',
        'yd³',
        'cubic yard',
        'cubic yards',
        'ml',
        'milliliter',
        'milliliters',
        'millilitre',
        'millilitres',
        'MLT',
        'cl',
        'centiliter',
        'centiliters',
        'centilitre',
        'centilitres',
        'CLT',
        'dl',
        'deciliter',
        'deciliters',
        'decilitre',
        'decilitres',
        'DLT',
        'l',
        'liter',
        'liters',
        'litre',
        'litres',
        'LTR',
        'dal',
        'decaliter',
        'decaliters',
        'decalitre',
        'decalitres',
        'hl',
        'hectoliter',
        'hectoliters',
        'hectolitre',
        'hectolitres',
        'cup',
        'cup',
        'cups',
    ];

    protected function instantiateTestQuantity()
    {
        return new Volume(1, 'm^3');
    }
}
